### ISSUE TITLE
Abbreviations

### ISSUE THREAD

**Issue by Barachia** [ARIA-VALUSPA/Flipper#2]
Behaviours containing text with apostrophes cause an error with missing variables.

Example:

`<behaviour class="eu.aria.dialogue.main.Behaviours">
     <argument name="response" value="Hello, I'm Alice. How are you doing?"  />
 </behaviour>`

**Comment by Siewart** [comment]
Solved.

for reference: AbstractValue.getStaticValue(String) wasn't able to parse this as string.

Fixed for the apostrophe case and will give an error if this occurs for another character and returns it as string in any case.
